spring:
  application:
    name: spring-boot-maven-archetype
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_SCHEMA:db}
    username: ${DB_USERNAME:dbuser}
    password: ${DB_PASSWORD:dbpass}
  profiles:
    active: "@spring.profiles.active@"
  jpa:
    hibernate:
      ddl-auto: validate